version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: F!!m%55+mb9N4Y
    ports:
      - "5432:5432"
